[package]

name = "podiff-review"
version = "0.0.1"
authors = [ "est31 <MTest31@outlook.com>" ]

[dependencies]
git2 = "0.3.1"
toml = "0.1.22"
rustc-serialize = "0.3.16"
hyper = "0.6.13"
url = "0.2.37"
